### ISSUE TITLE
Change Timestamp Data to a More Readable Type

### ISSUE THREAD

**Issue by eric-hedengren** [EricHedengren/FiberOpticsDatabasePeakStreaming#1]
Sqlite contains a data type called date time which can store information in this format: YYYY-MM-DD HH:MM:SS.SSS, which would be easily interpreted in contrast with epoch time.

**Comment by APMonitor** [comment]
I like that data type better. Any cost for disk space or memory for storing?

**Comment by eric-hedengren** [comment]
Probably. Additionally, we would need to format dates with python which could slow it down even more.

**Comment by eric-hedengren** [comment]
Converting values will be simple and fast when analyzing data, so we won't worry about storing a different type in the database.
