### ISSUE TITLE
Storage Size Too High Long Term

### ISSUE THREAD

**Issue by eric-hedengren** [EricHedengren/FiberOpticsDatabasePeakStreaming#2]
Create a long term storage for data points roughly every 30 seconds or more, short term possibly ten times a second that deletes itself after a few days.

**Comment by APMonitor** [comment]
I think we can store data every second or every 10 seconds long-term.

**Comment by APMonitor** [comment]
We need data at 10 Hz (10 per second) to transmit. We may need to include more averaging to reduce noise.
